# 2026 Group Standings Extraction

Pulls **group standings tables** (position, team, played, W/D/L, goals, points) from the [2026 FIFA World Cup](https://en.wikipedia.org/wiki/2026_FIFA_World_Cup) Wikipedia page.

Output: `Data/group_standings_2026.pkl` — a dictionary keyed by `Group A` … `Group L`.

This is separate from match-level scraping in `scripts/scrape_fixtures_2026.py`.

In [8]:
import pickle
from pathlib import Path

import pandas as pd

WIKIPEDIA_URL = "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup"
REQUEST_HEADERS = {"User-Agent": "FifaWorldCupAnalysis/1.0 (educational data project)"}
OUTPUT_PATH = Path("Data/group_standings_2026.pkl")
GROUP_LETTERS = list("ABCDEFGHIJKL")  # 12 groups in 2026 (48-team format)

In [9]:
all_tables = pd.read_html(WIKIPEDIA_URL, storage_options=REQUEST_HEADERS)
print(f"Loaded {len(all_tables)} tables from Wikipedia")

Loaded 139 tables from Wikipedia

In [10]:
def is_group_standings_table(df: pd.DataFrame) -> bool:
    """Detect Wikipedia group standings tables (4 teams, Pld/Pts columns)."""
    if len(df) != 4 or len(df.columns) < 8:
        return False
    cols = " ".join(str(c).lower() for c in df.columns)
    return "pld" in cols and "pts" in cols and "team" in cols


standings_indices = [i for i, t in enumerate(all_tables) if is_group_standings_table(t)]
print(f"Found {len(standings_indices)} group standings tables at indices: {standings_indices}")

if len(standings_indices) != len(GROUP_LETTERS):
    raise ValueError(
        f"Expected {len(GROUP_LETTERS)} group tables, found {len(standings_indices)}. "
        "Wikipedia page layout may have changed."
    )

Found 12 group standings tables at indices: [10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87]

In [11]:
def normalize_team_name(name: str) -> str:
    """Strip Wikipedia host marker, e.g. 'Mexico (H)' -> 'Mexico'."""
    return name.replace(" (H)", "").strip()


dict_table = {}
for letter, table_index in zip(GROUP_LETTERS, standings_indices):
    df = all_tables[table_index].copy()
    team_col = next(c for c in df.columns if "team" in str(c).lower())
    df = df.rename(columns={team_col: "Team"})
    df["Team"] = df["Team"].apply(normalize_team_name)
    dict_table[f"Group {letter}"] = df

list(dict_table.keys())

['Group A',
 'Group B',
 'Group C',
 'Group D',
 'Group E',
 'Group F',
 'Group G',
 'Group H',
 'Group I',
 'Group J',
 'Group K',
 'Group L']

In [14]:
for group_name, df in dict_table.items():
    print(f"===== {group_name} =====")
    display(df)

===== Group A =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Mexico,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,South Africa,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,South Korea,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Czech Republic,0,0,0,0,0,0,0,0,NaN

===== Group B =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Canada,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Bosnia and Herzegovina,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Qatar,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Switzerland,0,0,0,0,0,0,0,0,NaN

===== Group C =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Brazil,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Morocco,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Haiti,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Scotland,0,0,0,0,0,0,0,0,NaN

===== Group D =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,United States,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Paraguay,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Australia,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Turkey,0,0,0,0,0,0,0,0,NaN

===== Group E =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Germany,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Curaçao,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Ivory Coast,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Ecuador,0,0,0,0,0,0,0,0,NaN

===== Group F =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Netherlands,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Japan,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Sweden,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Tunisia,0,0,0,0,0,0,0,0,NaN

===== Group G =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Belgium,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Egypt,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Iran,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,New Zealand,0,0,0,0,0,0,0,0,NaN

===== Group H =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Spain,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Cape Verde,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Saudi Arabia,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Uruguay,0,0,0,0,0,0,0,0,NaN

===== Group I =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,France,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Senegal,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Iraq,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Norway,0,0,0,0,0,0,0,0,NaN

===== Group J =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Argentina,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Algeria,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Austria,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Jordan,0,0,0,0,0,0,0,0,NaN

===== Group K =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,Portugal,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,DR Congo,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Uzbekistan,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Colombia,0,0,0,0,0,0,0,0,NaN

===== Group L =====

,Pos,Team,Pld,W,D,L,GF,GA,GD,Pts,Qualification
0,1,England,0,0,0,0,0,0,0,0,Advance to knockout stage
1,2,Croatia,0,0,0,0,0,0,0,0,Advance to knockout stage
2,3,Ghana,0,0,0,0,0,0,0,0,Possible knockout stage based on ranking
3,4,Panama,0,0,0,0,0,0,0,0,NaN

In [13]:
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(OUTPUT_PATH, "wb") as output:
    pickle.dump(dict_table, output)

print(f"Saved {len(dict_table)} group tables to {OUTPUT_PATH}")

Saved 12 group tables to Data/group_standings_2026.pkl